# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-03 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20180603_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_plate',
            new_name='plate',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
